---
title: "Class 5 Participation"
author: "Pavan Hothi"
date: "2/10/2020"
output:
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r}

library(plotly)
library(tidyverse)


```



```{r}

head(diamonds)

diamonds.sample <- diamonds %>%
  sample_n(10000)

```



```{r}

plot_ly(data = diamonds, x= ~carat, y = ~price)
plot_ly(data = diamonds, x= ~cut, y = ~price)

diamonds %>%
  sample_n(100) %>%
plot_ly(data = ., x= ~carat, y = ~price, type = "scatter")


```



```{r}

plot_ly(data = diamonds, x= ~carat, y = ~price) %>%
  add_trace(p = ., type = "scatter")



```



### Styling

```{r}

plot_ly(data = diamonds.sample, x= ~carat, y = ~price, text = ~paste0("Price: $", price, "<br>Carat:", carat)) %>%
  add_trace(p = ., type = "scatter") %>%
  layout(xaxis = list(range = c(2.5, 5), title = "Carat"), 
         yaxis = list(title = "price"))


```



```{r}

lines.data <- data.frame(x = c(1:100), 
                         trace0 = rnorm(100, mean = 5)
                         ) %>%
  mutate(trace1 = log(trace0), 
         trace2 = trace0^2)


gather(data = lines.data, key = "trace", value = "val", -x)
lines.data.wide <- gather(data = lines.data, key = "trace", value = "val", -x)




plot_ly(data = lines.data, x = ~x) %>%
  add_trace(y = ~trace0, name = "Trace Zero", mode = 'lines') %>%
  add_trace(y = ~trace1, name = "Trace One", mode = 'lines+marker') %>%
  add_trace(y = ~trace2, name = "Trace Two", mode = 'marker')
  

plot_ly(data = lines.data.wide, x = ~x, y = ~val, color = ~trace, mode = "lines+markers") %>%
  layout(xaxis = list(ticks = "Outside", 
                      dtick = 10, 
                      ticklen = 5,
                      tickwidth = 2,
                      tickcolor = toRGB("pink"),
                      title = "X",
                      showgrid = FALSE, 
                      zeroline = FALSE),
yaxis = list(ticks = "Outside", 
                      dtick = 5, 
                      ticklen = 10,
                      tickwidth = 1,
                      tickcolor = toRGB("pink"),
                      title = "Val",
                      showgrid = FALSE, 
                      zeroline = FALSE),
      showlegend = TRUE,
legend = list(x = .15, y = .95), 
title = "Fake Data")









```




```{r}

cnt <- with(diamonds.sample, table(cut, clarity))

plot_ly(data = diamonds.sample, x= ~cut, y = ~clarity, z = ~cnt) %>%
  add_trace(type = "histogram2dcontour",
            contours = list(showlabels = T, labelfont = list(color = 'white')))


```



```{r}

plot_ly(data = diamonds.sample, y = ~price, color = ~cut, type = "box")
plot_ly(data = diamonds.sample, y = ~price, color = ~cut, type = "box")



```



```{r}

plot_ly(data = diamonds.sample, x = ~carat, y = ~price, z = ~depth)

```



```{r}

d.fig.1 <- diamonds.sample %>%
  ggplot(data = ., aes(x = price, y = depth, color = cut)) +
  geom_point() +
  stat_smooth()

ggplotly(d.fig.1)


```



